teaching_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import app_users
import curriculum

urlpatterns = [
    path('', include('app_users.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views

app_name='curriculum'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),

]

templates/curriculum/lesson_create.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Lesson Create {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Lesson Creation </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li class="disabled-text" >Lesson Create</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}

{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Create a Lesson</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
</section>


<form method="post" enctype="multipart/form-data">
  <div class="form-group">
  {% csrf_token %}
  {{form|crispy}}
  <input class="btn btn-success btn-lg btn-block" type="submit" value="Create">
  </div>
</form>

{% endblock %}

templates/curriculum/lesson_delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Lesson Delete {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Lesson Deletion </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">{{lessons.name}}</a></li>
            <li class="disabled-text" >Lesson Delete</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}



{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Delete {{lessons.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
</section>

<h3 class="mb-4" style="color:#ff5722;">Are you sure you want to delete {{lessons.name}} chapter?</h3>

<form method="post">
  {% csrf_token %}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Delete" class="btn btn-danger btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-warning btn-block">Cancel Deletion</a>
        </div>
  </div>
</form>

{% endblock %}

templates/curriculum/lesson_detail_view.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %} {{lessons.name}} {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" >Chapter-{{lessons.position}}: {{lessons.name}}</h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li class="disabled-text" >{{lessons.name}}</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}

{% block content %}

<section class="text-center">
    <h2 class="mb-0 mt-5 font-weight-bold" style="color:#ff5722;">Lecture Details</h2>
    <div class="row d-flex justify-content-center mb-3">
      <blockquote class="blockquote mt-0">
        <footer class="blockquote-footer">Created on {{lessons.created_at}} by <cite title="Source Title">{{lessons.created_by}}</cite></footer>
        </blockquote>
    </div>
    <!-- video -->
    <div class="row d-flex justify-content-center mb-3">
      <div id="player-overlay">
            <video controls>
                <source src="{{lessons.video.url}}"  type="video/mp4">
              </video>
      </div>
    </div>
    <!-- download cards -->
    <div class="row d-flex justify-content-center mb-3 mt-3">
      <!-- download presentations -->
                <div class="col-md-4 mb-4 mt-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Download Presentations</h5>
                      {% if lessons.ppt %}
                      <p class="card-text">Download presentations from the lecture</p>
                      <a href="{{lessons.ppt.url}}" download>
                      <button type="button" class="button-les"><span>Get Files</span></button>
                      </a>
                      {% else %}
                      <p class="card-text" > No PPT available</p>
                      {% endif %}

                    </div>
                  </div>
                </div>
      <!-- download notes -->
                <div class="col-md-4 mb-4 mt-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Download Notes</h5>
                      {% if lessons.Notes %}
                      <p class="card-text">Download notes from the lecture</p>
                      <a href="{{lessons.Notes.url}}" download>
                      <button type="button" class="button-les"><span>Get Files</span></button>
                      </a>
                      {% else %}
                      <p class="card-text">Notes not available</p>
                      {%endif%}

                    </div>
                  </div>
                </div>
      <!-- download video -->
                <div class="col-md-4 mb-4 mt-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Download Video</h5>
                      <p class="card-text">Download Video from the lecture</p>
                      <a href="{{lessons.video.url}}" download>
                      <button type="button" class="button-les"><span>Get Files</span></button>
                      </a>
                    </div>
                  </div>
                </div>
    </div>
    <!-- update and delete button -->
    <div class="row d-flex justify-content-center mb-3 mt-3">
        {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
        <div class="col-md-6 mb-3 text-center">
            <a href="{% url 'curriculum:lesson_update' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-warning btn-lg mr-4 btn-block">Update Lesson</a>
        </div>
        <div class="col-md-6">
            <a href="{% url 'curriculum:lesson_delete' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-danger btn-lg mr-4 btn-block"> Delete Lesson </a>
        </div>
        {% endif %}
      </div>
</section>

<hr class="my-5" style="color:#ff5722;">

<!-- Comments section -->
<section >
    <h2 class="mb-4 mt-5 font-weight-bold" style="color:#ff5722;">Questions And Queries</h2>
    <h4 class="mt-2 font-weight-bold" style="color:#ff5722;">Post your comment or question below:</h4>
    <br><br>
    <div class="container row">
      <div class="col-md-6">
                              <form method="post">
                                    <div class="form-group">
                                    {% csrf_token %}
                                    {{form|crispy}}
                                    <input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">
                                    </div>
                              </form>

      </div>
    </div>
    <div class="row">
      {% for comment in lessons.comments.all %}
      <div class="col-md-8 mt-2 mb-2">
                      <div class="media border p-3">
                          <img src="{% static 'Images/user_avatar.png' %}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                          <div class="media-body">
                                    <h4>{{comment.author}} <small><i>Posted on {{comment.date_added}}</i></small></h4>
                                    <p>{{comment.body}}</p>
                            {% for reply in comment.replies.all %}
                                        <div class="media p-3">
                                                <img src="{% static 'Images/user_avatar.png' %}" alt="Jane Doe" class="mr-3 mt-3 rounded-circle" style="width:45px;">
                                        <div class="media-body">
                                                <h5>{{reply.author}} <small><i>Posted on {{reply.date_added}}</i></small></h5>
                                                <p>{{reply.reply_body}}</p>
                                          </div>
                                        </div>
                            {% endfor %}
                            <!-- form to post reply -->
                            <form method="post">
                                  <input type="hidden" name="comment.id" value="{{comment.id}}">
                                  <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
                                  {% csrf_token %}
                                  {{form2.as_p}}
                                  <input type="submit" name="form2" value="Add Reply" class="btn btn-warning btn-sm">
                            </form>
                          </div>
                  </div>
      </div>
      {% endfor %}
    </div>


</section>

{%endblock%}

templates/curriculum/lesson_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{subjects.name}} {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > {{subjects.name}} </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=subjects.standard.slug %}">{{subjects.standard}}</a></li>
            <li class="disabled-text" >{{subjects.name}}</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}


{% block content %}
<section id="best-features" class="text-center">
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Dive Deeper</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8 mb-5">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
              <!-- class row2 for cards -->
              <div class="row d-flex justify-content-center mb-3">
                {% for lesson in subjects.lessons.all %}
                <div class="col-sm-4 mb-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Chapter-{{lesson.position}}: {{lesson.name}}</h5>
                      <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                      <a href="{% url 'curriculum:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}" >
                      <button type="button" class="button-les"><span>Get Lectures</span></button>
                      </a>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
        <div class="row d-flex justify-content-center mb-3">
          {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
           <a href="{% url 'curriculum:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}"><button type="button" class="btn btn-success btn-lg btn-bloc" > Add new Lesson </button> </a>
          {% endif %}
        </div>

</section>






{%endblock%}

templates/curriculum/lesson_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Lesson Update {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Lesson Update </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">{{lessons.name}}</a></li>
            <li class="disabled-text" >Lesson Update</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}


{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Update {{lessons.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
</section>


<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form|crispy}}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Update" class="btn btn-warning btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-danger btn-block">Cancel Update</a>
        </div>
</div>
</form>

{% endblock %}

templates/curriculum/standard_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Standards {% endblock %}


{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Standards </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li class="disabled-text">Standards</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}

{% block content %}
<!-- section 1 for standards-->

<section id="best-features" class="text-center">
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Dive Into Learning</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
              <!-- class row2 for cards -->
              <div class="row">
                      {% for standard in standards %}
                      <div class="col-md-4 d-flex mb-5 justify-content-center">
                        <div class="card card-std text-center" style="width: 20rem;">
                          <div class="card-body text-center">
                            <h4 class="card-title" style="color:#ff5722;">{{standard.name}}</h4>
                            <p class="card-text">{{standard.description|truncatechars:75}}</p>
                            {% if user.is_authenticated %}
                            <a href="{% url 'curriculum:subject_list' slug=standard.slug %}" class="btn btn-primary" style="background-color:#00bcd4;">Lets get started</a>
                            {%else%}
                            <p>Register or login to start learning</p>
                            <a href="{% url 'user_login' %}" class="btn btn-std" style="background-color:#00bcd4;">Login</a>
                            <a href="{% url 'register' %}" class="btn btn-primary" style="background-color:#00bcd4;">Register</a>
                            {%endif%}
                          </div>
                        </div>
                      </div>
                      {% endfor %}
              </div>
</section>

{%endblock%}

templates/curriculum/subject_list_view.html
  {% extends 'base.html' %}
  {% load static %}
  {% block title %} Standards {% endblock %}


  {% block image_block %}
  <header class="info-header">
    <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
      <div class="row d-flex justify-content-center text-center">
        <div class="col-md-10 text-white">
          <!-- heading -->
          <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Subjects </h2>
          <div class="row d-flex justify-content-center text-center">
            <ul class="breadcrumb">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
              <li class="disabled-text" >{{standards.name}}</li>
            </ul>
          </div>

          <!-- divider -->
          <hr style="color:#ff5722;">

          <!-- description -->
          <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Deleniti
                    consequuntur.</h4>
    </div>
  </header>
  {% endblock %}

  {% block content %}
  <section id="best-features" class="text-center">
                <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Master The Subject</h2>
                <!-- class row for description-->
                <div class="row d-flex justify-content-center mb-4">
                  <!-- class column -->
                  <div class="col-md-8 mb-5">
                    <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                      hic
                                      provident nulla repellat
                                      facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                      est
                                      sit pariatur.</p>
                  </div>
                </div>
                <div class="col-md-12 justify-content-center mb-5">
                  <h4 class="card-title" style="color:#ff5722;">Time-Table</h4>
                  <table id="class-time-table">
                    <tr>
                      <th></th>
                      {% for slot in slots %}
                      <th scope="row">{{slot.start_time}}</th>
                      {% endfor %}
                    </tr>
                    <tr>
                      <th>Monday</th>
                      {%for slot in standards.standard_slots.all%}
                      {%if slot.day.id == 1 %}
                        <td>{{slot.slot_subject}}</td> 
                      {% endif %}
                      {% endfor %}
                    </tr>
                    <tr>
                      <th>Tuesday</th>
                      {%for slot in standards.standard_slots.all%}
                      {%if slot.day.id == 2 %}
                        <td>{{slot.slot_subject}}</td> 
                      {% endif %}
                      {% endfor %}
                    </tr>
                    <tr>
                      <th>Wednesday</th>
                      {%for slot in standards.standard_slots.all%}
                      {%if slot.day.id == 3 %}
                        <td>{{slot.slot_subject}}</td> 
                      {% endif %}
                      {% endfor %}
                    </tr>
                    <tr>
                      <th>Thursday</th>
                      {%for slot in standards.standard_slots.all%}
                      {%if slot.day.id == 4 %}
                        <td>{{slot.slot_subject}}</td> 
                      {% endif %}
                      {% endfor %}
                    </tr>
                    <tr>
                      <th>Friday</th>
                      {%for slot in standards.standard_slots.all%}
                      {%if slot.day.id == 5 %}
                        <td>{{slot.slot_subject}}</td> 
                      {% endif %}
                      {% endfor %}
                    </tr>
                  </table>
                </div>
                <!-- class row2 for cards -->
                <div class="row d-flex justify-content-center mb-3">
                {% for subject in standards.subjects.all %}
                <div class="card mb-5 mr-4 ml-4 box-shadow-hover" style="max-width: 500px;">
                  <div class="row no-gutters">
                            <div class="col-md-4">
                              <img src="{{subject.image.url|default_if_none:'#'}}" class="card-img" alt="No image found" height="200px" width="200px">
                            </div>
                            <div class="col-md-8">
                              <div class="card-body">
                                <h4 class="card-title" style="color:#ff5722;">{{subject.name}}</h4>
                                <p class="card-text">{{subject.description|truncatechars:75}}</p>
                                <p class="card-text"><small class="text-muted"></small></p>
                                    <a href="{% url 'curriculum:lesson_list' slug=subject.slug standard=standards.slug %}"><button class="button-les"> <span> Get Lessons</span></button></a>
                              </div>
                            </div>
                  </div>
                  </div>
                {% endfor %}
                </div>
  </section>
  {%endblock%}